routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'contacts')->name('index');

Route::resource('contacts', 'ContactsController', ['except' => ['show']]);

Route::get('contacts/find', 'ContactsController@find')->name('contacts.find');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
      'name',
      'phone_number'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ContactsController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Illuminate\Http\Request;

class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $contacts = Contact::orderBy('name')->get();
      return view('contacts.index', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('contacts.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $validate = $request->validate([
        'name' => 'required',
        'phone_number' => 'required'
      ]);
      Contact::create($request->only('name', 'phone_number'));
      return redirect()->route('index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
      return view('contacts.form', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact)
    {
      $validate = $request->validate([
        'name' => 'required',
        'phone_number' => 'required'
      ]);
      $contact->update($request->only('name', 'phone_number'));
      return redirect()->route('index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $contact->delete();
        return redirect()->route('index');
    }

    public function find(Request $request) {
      $findQuery = $request->find_query;
      $contacts = Contact::orderBy('name')
                    ->where('name', 'LIKE', '%' . $findQuery . '%')
                    ->orWhere('phone_number', 'LIKE', '%' . $findQuery . '%')
                    ->get();
      return view('contacts.index', [
        'findQuery' => $findQuery,
        'contacts' => $contacts,
        'isFilter' => true
      ]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/contacts/form.blade.php
@extends('master')

@section('content')
  <h2>Добавить контакт</h2>
    @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif
  @isset ($contact)
    <form action="{{ route('contacts.update', $contact->id) }}" method="POST">
      @csrf
      {{method_field('PUT')}}
      <input type="text" name="name" value="{{ $contact->name }}" autocomplete="off">
      <input type="text" name="phone_number" value="{{ $contact->phone_number }}" autocomplete="off">
      <input type="submit" value="Сохранить">
    </form>
  @endisset
  @empty ($contact)
    <form action="{{ route('contacts.store') }}" method="POST">
      @csrf
      <input type="text" name="name" autocomplete="off">
      <input type="text" name="phone_number" autocomplete="off">
      <input type="submit" value="Добавить">
    </form>
  @endempty
@endsection

resources/views/contacts/index.blade.php
@extends('master')

@section('content')
  <h2>Поиск по записям</h2>
  <form action="{{ route('contacts.find') }}" method="GET">
    @csrf
    <input type="text" name="find_query" value="{{ $findQuery or ''}}" autocomplete="off">
    <input type="submit" value="Найти">
    @isset ($isFilter)
      <a href="{{ route('index') }}">Сбросить фильтр<a>
    @endisset
  </form>
  <h2>Список контактов</h2>
  <table>
    <thead>
      <tr>
        <td>№</td>
        <td>ФИО</td>
        <td>Номер телефона</td>
        <td>Настроить</td>
      </tr>
    </thead>
    <tbody>
      @foreach( $contacts as $contact)
      <tr>
        <td>{{ $loop->iteration }}</td>
        <td>{{ $contact->name }}</td>
        <td>{{ $contact->phone_number }}</td>
        <td>
          <form action="{{ route('contacts.destroy', $contact->id) }}" method="POST">
            <a href="{{ route('contacts.edit', $contact->id) }}">Изменить</a>
            @csrf
            {{ method_field('DELETE') }}
            <button type="submit">Удалить</button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
@endsection

resources/views/master.blade.php
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
    table {
      border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid black;
    }
  </style>
</head>
<body>
  <h1>Записаня книжка</h1>
  <ul>
    <li>
      <a href="{{ route('contacts.create') }}">Новый контакт</a>
    </li>
    <li>
      <a href="{{ route('index') }}">Список контактов</a>
    </li>
  </ul>
  @yield('content')
</body>
</html>